export const projects = [
  {
    title: 'SOCIAL BLOGGING BLOG',
    description: "Developed a React app that features realtime data from Firebase and server-side rendering with Next.js. Authors can create content under their custom username, then publish publicly with SEO - friendly rendering, while readers can heart or like posts in real time.Implemented advanced SSR, SSG, and ISR techniques in the Next framework.Deployed on Vercel",
    image: '/images/1.png',
    tags: ['React', 'Next'],
    source: 'https://github.com/Prasheelreddy/nextBlog',
    visit: 'https://next-blog-psi-gold.vercel.app/',
    id: 0,
  },
  {
    title: 'MUSIC PLAYER',
    description: "a music app with features like playlists, audio player, shuffle, and more! Used a modern stack of tools: React, Next.js, Typescript, and Postgres. Code reusable UI components, database schemas and migrations, API calls with serverless functions, and deploy it on vercel ",
    image: '/images/spotify.jpg',
    tags: ['React', 'Next', 'Prisma(ORM)', "PostgreSQL"],
    source: 'https://github.com/Prasheelreddy/music-player',
    visit: 'https://music-player-three-sandy.vercel.app/',
    id: 1,
  },
  {
    title: 'FUN BATTLE PLAYER',
    description: "Fun application implemented with reactjs & Git API that accepts two github accounts and calculates the winner and loser.Displays top github accounts on python, js, css",
    image: '/images/3.jpg',
    tags: ['React Hooks', 'GitAPI', 'AWS'],
    source: 'https://github.com/Prasheelreddy/TWO-PLAYER-BATTLE',
    visit: 'https://battleplayer.click/',
    id: 2,
  },
  {
    title: 'TWITTER PAGE CLONE(In Development)',
    description: "Built with TypeScript and GraphQL's type systems to create full-stack, fully-type-checked codebases.Able to create new tweets.Able to like and unlike tweets.",
    image: '/images/1.png',
    tags: ['React', 'Typescript', 'Graphql'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
];
