export const projects = [
  {
    title: 'SOCIAL BLOGGING BLOG',
    description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
    image: '/images/1.png',
    tags: ['React', 'Next'],
    source: 'https://github.com/Prasheelreddy/nextBlog',
    visit: 'https://next-blog-psi-gold.vercel.app/',
    id: 0,
  },
  {
    title: 'MUSIC PLAYER',
    description: "While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: '/images/spotify.jpg',
    tags: ['React', 'Next', 'Prisma(ORM)', "PostgreSQL"],
    source: 'https://github.com/Prasheelreddy/music-player',
    visit: 'https://music-player-three-sandy.vercel.app/',
    id: 1,
  },
  {
    title: 'FUN BATTLE PLAYER',
    description: "Fun application implemented with reactjs & Git API that accepts two github accounts and calculates the winner and loser.Displays top github accounts on python, js, css",
    image: '/images/3.jpg',
    tags: ['React Hooks', 'GitAPI', 'AWS'],
    source: 'https://github.com/Prasheelreddy/TWO-PLAYER-BATTLE',
    visit: 'https://battleplayer.click/',
    id: 2,
  },
  {
    title: 'TWITTER PAGE CLONE',
    description: "Built with TypeScript and GraphQL's type systems to create full-stack, fully-type-checked codebases.Able to create new tweets.Able to like and unlike tweets.",
    image: '/images/1.png',
    tags: ['React', 'Typescript', 'Graphql'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
];
